@echo off
echo Stopping the existing app...
taskkill /F /IM node.exe

echo Pulling latest changes from the repository...
git pull origin main

echo Installing dependencies...
npm install

echo Building the project...
npm run build

echo Starting the app...
start /B node app.js
